spring.application.name=backend

# Conexao com o banco de dados PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/duotune_db
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Configuracoes de E-mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=duotune.ufrn@gmail.com
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true